language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -q tox
  - pip install -q coveralls

script: coverage run --source=resizeimage setup.py test

after_success:
  coveralls
